### PR TITLE
Fix removing a reaction from a discussion post

### LINKED ISSUE #529: Unable to remove a reaction after adding one
Reproduction:

1. Create or view a post under Discussion
2. Add a reaction
3. Click same reaction to remove it; it does not work

Browser shows an error:

```
DELETE http://localhost:3000/api/reactions/e73138ec51740a4d6314b45937c15b9f?reaction%5Bvalue%5D=%3Asmirk%3A&reaction%5Breactable_id%5D=616727a00bb4027060765cad&reaction%5Breactable_type%5D=Post
```

results in `NS_ERROR_DOM_BAD_URI`

### PR DESCRIPTION
**Pull request by bklang**
This fixes removing emoji from posts. It extends the whitelist of HTTP verbs. Future work should consider whether allowing all origins is a good idea

Fixes #529

### CODE REVIEW

File: backend/app/models/reaction.rb [hunk 1]
```diff
@@ -18,15 +18,17 @@ def similar_to(reaction)
...
       collection.aggregate(aggregation.pipeline).map do |reaction|
+        # A real ID is only required when the current user has reacted. Otherwise the value is meaningless
+        # Use a random string to try to demonstrate that
         {
-          id: SecureRandom.hex(16), # needed for Ember UI - is there a better way?
+          id: (reactions_for_user[reaction["_id"]] || SecureRandom.hex(16)).to_s,
           value: reaction["_id"],
           count: reaction["count"],
-          participated: reactions_for_user.include?(reaction["_id"])
+          participated: reactions_for_user.keys.include?(reaction["_id"])
```
Comment (benlangfeld) [inline backend/app/models/reaction.rb]:
```suggestion
          participated: reactions_for_user.key?(reaction["_id"])
```

to satisfy the linter.

**Review by benlangfeld — APPROVED** [review]
