### PR TITLE
Fix/no map reduce for reactions

### LINKED ISSUE #480: Chat/discussion feature is broken
The loading icon (see attached) appears forever.  We should either fix or hide this feature.
Screen Shot 2021-10-12 at 2 09 06 PM

### PR DESCRIPTION
**Pull request by bklang**
Related to #480

### CODE REVIEW

File: backend/app/models/reaction.rb [hunk 1]
```diff
@@ -1,88 +1,34 @@
...
 
-  class << self
-    def similar_to(reaction)
-      where(
-        value: reaction.value,
-        reactable_id: reaction.reactable_id,
-        reactable_type: reaction.reactable_type
-      )
-    end
+  scope :similar_to, ->(reaction) do
```
Comment (benlangfeld) [inline backend/app/models/reaction.rb]: Did you end up using this?

Comment (bklang) [reply backend/app/models/reaction.rb]: yes, it is used in other parts of the application already. I converted it from a class method to a scope

**Review by benlangfeld — APPROVED** [review]
