### PR TITLE
Fix patterns for multiple checkins

### LINKED ISSUE #547: Patterns charts broken on multi-checkin days
The patterns charts seem to be having trouble resolving days that have multiple checkins. It tries to show both values on the chart at the same X position, and the tooltip appears to be showing "undefined" for any subsequent instances of a value.

On the individual history charts it looks like we average multiple checkins into a single value for the day, extending that same behavior to the patterns charts would be consistent and solve the issue well.

image

### PR DESCRIPTION
**Pull request by haydenrou**
#547 

Before:
Screenshot 2021-10-27 at 10 04 23 AM

After:
Screenshot 2021-10-27 at 10 20 52 AM

### CODE REVIEW

**Review by lmerriam — APPROVED** [review]
Looks good!

File: backend/app/services/charts_pattern.rb [hunk 1]
```diff
@@ -67,11 +67,16 @@ def data(chart)
...
+    collected_data =
+      if %w[conditions symptoms treatments].include? category
+        static_trackables_coordinates(category, scoped_checkins.map(&:id), id)
+      else
+        health_factors_trackables_coordinate(category, scoped_checkins, id)
+      end
+
+    average = collected_data.inject(0.0) { |result, datum| result + datum[:y].to_f } / collected_data.count
+
+    [{ x: collected_data[0]&.fetch(:x), y: average }]
```
Comment (haydenrou) [inline backend/app/services/charts_pattern.rb:79]: The way we collect this data means that the `x` value - which is the condition, symptom or treatments name - I believe will always be the same for all this `collected_data`. Hence accessing `[0]`.

**Review by phylum — APPROVED** [review]

File: backend/app/services/charts_pattern.rb (hunk 1 above)
Comment (compwron) [reply backend/app/services/charts_pattern.rb:79]: Seems reasonable. Is it possible to write a test for this?

**Review by compwron — APPROVED** [review]

File: backend/app/services/charts_pattern.rb (hunk 1 above)
Comment (haydenrou) [reply backend/app/services/charts_pattern.rb:79]: @compwron would this not having tests hold it up being merged? I don't want to push back on them however I did want to get this fix out since we introduced the bug last week, but there are currently no tests written for the charts code so this small change would require writing this test from the top down. How would you feel about splitting the tests out into a separate issue/task?

If not, I am happy to do them but it may have to wait a few days and I wasn't sure if we wanted the bug fix out there ASAP.

**Comment by compwron** [comment]
@haydenrou fair enough. I would really like more tests but let's not delay for them this time.

File: backend/app/services/charts_pattern.rb (hunk 1 above)
Comment (compwron) [reply backend/app/services/charts_pattern.rb:79]: this is deployed to prod!
